export const AUTH_INITIATE_SIGNUP = "AUTH_INITIATE_SIGNUP";
export const AUTH_SIGNUP_SET_ERROR = "AUTH_SIGNUP_SET_ERROR";

export const AUTH_SET = "AUTH_SET";
export const AUTH_INITIATE_INITIAL_CHECK = "AUTH_INITIATE_INITIAL_CHECK";

export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";

export const AUTH_INITIATE_LOGIN = "AUTH_INITIATE_LOGIN";
export const AUTH_LOGIN_SET_ERROR = "AUTH_LOGIN_SET_ERROR";
