apiVersion: apps/v1
kind: Deployment
metadata:
  name: satoshi-data-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: satoshi-data
  template:
    metadata:
      labels:
        app: satoshi-data
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: satoshi-data
          image: satoshi_data:0.0.1
          env:
            - name: NATS_URL
              value: "http://satoshi-nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: satoshi
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: satoshi-secrets
                  key: JWT_SECRET
            - name: APP_URL
              value: "https://satoshi.vgdesign.ir/"
            - name: ENV
              value: "development"
            - name: DB_HOST
              value: "satoshi-data-mongo-srv"
            - name: DB_PORT
              value: "27017"
            - name: DB_NAME
              value: "data_db"
            - name: DB_USER
              value: "data_dbu"
            - name: DB_PASSWORD
              value: "S3cr3tPasvv0rd"
          volumeMounts:
            - mountPath: /usr/src/data
              name: data-vol
      volumes:
        - name: data-vol
          hostPath:
            path: /home/amin/projects/environments/satoshi/src/data
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: satoshi-data-srv
spec:
  selector:
    app: satoshi-data
  type: ClusterIP
  ports:
    - name: satoshi-data
      protocol: TCP
      port: 3000
      targetPort: 3000
